### ISSUE TITLE
[RA]: Requisiti obbligatori funzionali 

### ISSUE THREAD

**Issue by EduBic** [LeafSWE/clips#25]
- [x] RObbF10.1 - L’applicazione deve fornire un elenco dei POI raggiungibili all’interno dell’edificio in cui si trova l’utente _(Aggiungere una categoria TUTTE che raccoglie tutti i POI dell'edificio, Cliccare su NOME EDIFICIO -> mostra tutti i POI ogni POI se selezionato mostra la propria descrizione)_
- [x] RObbF10.2.4 - L’applicazione deve fornire la descrizione di uno specifico POI _(vedi sopra)_
- [x] RObbF8.1.4 - L’applicazione deve segnalare un messaggio d’errore esplicito nel caso in cui venga inserita una destinazione non prevista dal sistema _(decidere se mostrare solo il TOAST 'Nessun risultato' o schermata con scritto 'Nessun risultato')_ 
- [x] RObbF8.6 - L’applicazione deve avvisare l’utente con un messaggio d’errore esplicito nel caso in cui si avvii una navigazione con connessione Internet del dispositivo non attiva _(avviso DIALOG che la connessione non è attiva e la navigazione non è garantita)_
- [x] RObbF10.9 - L’applicazione deve avvisare l’utente con un messaggio d’errore esplicito nel caso in cui si acceda alle informazioni dell’edificio mappato in cui si trova con connessione Internet del dispositivo non attiva _(vedi sopra)_
- [x] RObbF10.10 - L’applicazione deve avvisare l’utente con un messaggio d’errore esplicito nel caso in cui si acceda alle informazioni dell’edificio mappato in cui si trova e la mappa dell’edificio installata nel dispositivo differisce dall’ultima versione online _(vedi sopra)_
- [x] RObbF11.1.1.3 - L’applicazione deve permettere di scegliere il percorso più veloce _(modifica in 'permettere di scegliere' in 'fornire')_
- [x] RObbF9.6 - L'applicazione deve permettere di rilevare l'area coperta dal segnale dei beacon rilevati @black2279

**Comment by black2279** [comment]
A questo indirizzo trovare la situazione attuale dei requisiti:

http://tracyswe-leafgruppo.rhcloud.com/tracy/latex/RequirementApportion

**Comment by black2279** [comment]
Ho un dubbio sul requisito http://tracyswe-leafgruppo.rhcloud.com/tracy/requirement/83 è soddisfatto o c'è da implementare una funzionalità?

**Comment by tfederico** [comment]
@black2279 A parer mio è implementato

**Comment by black2279** [comment]
Ok allora me ne occupo io

**Comment by mzanella** [comment]
Se non sbaglio RObbF10.10 è già stato implementato da @o5k1 ma non credo sia mai stato provato. Gli altri a parte RObbF9.6 sono stati implementati nel branch f/navigazione2
