### ISSUE TITLE
Fallimento HomeActivity vuota

### ISSUE THREAD

**Issue by EduBic** [LeafSWE/clips#27]
Il crash si verifica ogni qualvolta si lascia la home prima che questa rilevi un edificio.
### Procedura:
1. Tutto attivato Wifi etc.
2. Avvio l'app
3. Effettuo un passaggio nella sezione preferenze prima che l'edificio sia rilevato
### Eccezione sollevata

![errore](https://cloud.githubusercontent.com/assets/13170564/15690117/4f83a46a-2782-11e6-877e-6e1be29ea797.JPG)

**Comment by o5k1** [comment]
Penso di aver risolto. Però dovrei fare un merge (ho lavorato sul development) e sono pieno di sonno, quindi preferisco fare domani mattina

**Comment by o5k1** [comment]
Risolto?

**Comment by EduBic** [comment]
Sì
