### ISSUE TITLE
Fix mappe remote

### ISSUE THREAD

**Issue by o5k1** [LeafSWE/clips#28]
Se viene effettuato il download di una mappa remota e poi si passa alla Activity delle mappe locali, la mappa scaricata non appare tra le mappe locali.

**Comment by oeconti** [comment]
Risolto. Fai pure una prova.

**Comment by o5k1** [comment]
Se tento di scaricare la mappa del Vallisneri, viene lanciata un'eccezione che manda in crash l'app.
Suppongo problematiche sul DB @black2279.

Allego stacktrace.
[err_log.txt](https://github.com/LeafSWE/clips/files/298763/err_log.txt)

**Comment by black2279** [comment]
Su che branch stai lavorando?

**Comment by black2279** [comment]
A me da le eccezioni ma non crasha.
Vengono lanciate perchè le tuple che si stanno inserendo sono già presenti. Esempio Categorie o EdgeType.

**Comment by o5k1** [comment]
l'avevo provato su f/fix_back_button_HomeActivity

**Comment by oeconti** [comment]
Questa issue è relativa al caricamento di una mappa dopo il download della stessa. Si può chiudere?

**Comment by o5k1** [comment]
su f/remote_map_load_fix continua a lanciare eccezioni e crashare quando tento di scaricare la mappa  del Vallisneri

**Comment by o5k1** [comment]
Qualcuno se ne sta occupando?
