### ISSUE TITLE
Fix logger

### ISSUE THREAD

**Issue by tfederico** [LeafSWE/clips#29]
Bug grafico dopo aver registrato un log, se si cerca di tornare indietro con il tasto back si torna nella HomeActivity, se si preme di nuovo indietro torna nella lista dei log e continua così in un loop.

**Comment by tfederico** [comment]
Allego video dimostrativo
[video_2016-06-01_21-07-31.zip](https://github.com/LeafSWE/clips/files/294175/video_2016-06-01_21-07-31.zip)

**Comment by oeconti** [comment]
Sicuri sia un bug del Logger e non della HomeActivity?

**Comment by mzanella** [comment]
Anche secondo me il back dell'HomeActivity non è bene gestito... Infatti senza entrare nei log, premendo il tasto back nell'home activity che ha caricato i dati si viene riportati all'homeActivity vuota

**Comment by mzanella** [comment]
@tfederico  @oeconti  propongo fix nel branch f/fix_back_button_HomeActivity

**Comment by o5k1** [comment]
Mi sembra risolto, per me si può chiudere
