### ISSUE TITLE
Fallimento HomeActivity vuota Internet disattivato

### ISSUE THREAD

**Issue by EduBic** [LeafSWE/clips#30]
### Procedura
1. Attivare solo il bluetooth
2. Avviare l'applicazione (assicurarsi che abbia già la mappa installata)
3. Accedere alla sezione gestione mappe prima che siano caricate le informazioni dell'edificio

Il bug si presenta sia con Lollipop sia con Kitkat

![capture](https://cloud.githubusercontent.com/assets/13170564/15723468/d0fe5970-2842-11e6-9724-8ab1a0861317.JPG)

**Comment by mzanella** [comment]
il bug in teoria si verifica perchè viene creato l'alert no internet ma l'activity da cui è creato non è più presente

**Comment by EduBic** [comment]
Il bug si verifica ancora:
1. Avvio l'app una volta per scaricare la mappa.
2. Chiudo l'app e l'arresto completamente
3. Mi assicuro di avere Bluetooth attivato e nessuna connessione a Internet attiva
4. Avvio l'app
5. dal menu entro in "gestione mappe" poi esco usando il torna indietro in alto a sinistra.
6. Aspetto anche qualche minuto perché dal monitoring passi al ranging
7. Parte il ranging e viene sollevata l'eccezione poco dopo

Qui gli avvisi prima del crash 
![capture](https://cloud.githubusercontent.com/assets/13170564/15753759/1be35b18-28f5-11e6-9a6c-b397e83e2957.JPG)

**Comment by EduBic** [comment]
Novità:
Ho fatto la stessa identica procedura ma sta volta ho utilizzato il pulsante di android "Indietro", il ranging parte, l'edificio è caricato e mi viene mostrato l'allert e tutto funziona.

**Comment by EduBic** [comment]
Il bug nel branch bug_fix#30 è stato risolto, in attesa del merge...

**Comment by oeconti** [comment]
Si può mergiare?

**Comment by oeconti** [comment]
Mergiato.
