### ISSUE TITLE
Rotazione schermo fallita

### ISSUE THREAD

**Issue by EduBic** [LeafSWE/clips#31]
L'applicazione attualmente non supporta la modalità landscape del display, tentare il passaggio provoca un brusco crash.

**Comment by mzanella** [comment]
Dovrei aver risolto nel branch f/bug_fix_#31. Tale soluzione ha 2 problemi minori però:
- beacon power area si vede schiacciatissimo alla rotazione dello schermo
- logging activity non fa più vedere i beacon registrati fino a quel momento

@oeconti @black2279 sapete come risolvere o per quelle due activity blocchiamo lo schermo?

**Comment by black2279** [comment]
Per me si può bloccare tutto in portrait

**Comment by mzanella** [comment]
Il resto funziona se guardi sul branch f/bug_fix_#31... Il problema è che l'immagine viene piccolissima

**Comment by mzanella** [comment]
Se vi va bene basta mergiare il branch comunque... ho dsattivato il landscape da quelle due activity

**Comment by black2279** [comment]
Ok perfetto.

**Comment by oeconti** [comment]
Anche per me va bene.

**Comment by oeconti** [comment]
Mergiato.
