### ISSUE TITLE
PoiDescriptionActivity - Descrizione Mancante

### ISSUE THREAD

**Issue by oeconti** [LeafSWE/clips#32]
Qual'è la descrizione di questa classe?

**Comment by mzanella** [comment]
potrebbe essere tipo cosi:
_PoiDescriptionActivity è la classe che si occupa di gestire la descrizione di un POI presente nell'edificio associato al beacon rilevato, in modo che vengano fornite all'utente le informazioni presenti nel database associate a quello specifico POI_

**Comment by oeconti** [comment]
Ottimo, l'ho aggiunta. Grazie
