### ISSUE TITLE
Fix frecce in landscape

### ISSUE THREAD

**Issue by mzanella** [LeafSWE/clips#33]
nel caso in cui il telefono si posizionato in landscape le frecce come sono ora non vanno bene. in questo caso o si blocca l'orientamento dell'activity oppure basta fare un if sull'orientamento e aggiustare i gradi

**Comment by mzanella** [comment]
ok dovrebbe essere messo a posto sul branch f/fix_arrow_direction... Se qualcuno mi da un check chiudo la issue

**Comment by EduBic** [comment]
Ho testato il comportamento della bussola.

Tutto a posto nel caso lo schermo è normale mentre nell'uso dello schermo ruotato tutto è invertito: per esempio invece di "DRITTO" mi indica "VOLTATI" invece di "RUOTA A SINISTRA" mi indica "RUOTA A DESTRA"

**Comment by o5k1** [comment]
Blocchiamo l'Activity in portrait

**Comment by mzanella** [comment]
A me segna la stessa direzione invece sia lanscape che portrait

**Comment by EduBic** [comment]
Vero ho provato con il telefono Lollipop e quello me le mostra giuste. 

Probabilmente è il posizionamento dei sensori, forse il samsung mini dispone già di una correzione della direzione e quindi sballa tutto.

EDIT: Ora ho capito, la modalità landscape è di due tipi, o lo ruoti a sinistra e va bene o lo ruoti a destra e va tutto al contrario (caso non previsto)

**Comment by mzanella** [comment]
Voi riuscite a mettere il callulare anche in reverse portrait?

**Comment by mzanella** [comment]
Comunque ho aggiunto sia il caso reverse landscape che reverse portrait

**Comment by EduBic** [comment]
Molto bene ora tutte coincidono
