### ISSUE TITLE
Test che falliscono

### ISSUE THREAD

**Issue by mzanella** [LeafSWE/clips#34]
ci sono alcuni test che falliscono e che non riesco a sistemare. In particolare sono:

<ul>
<li> BuildingServiceTest:</li>
<ul>
<li>shouldRetrieveARemoteMap</li>
<li>shouldRetrieveAllRemoteBuildingsInformation</li>
<li>shouldUpdateMap</li>
<li>shouldVerifyIfMapIsUpdated</li>
<li>shouldVerifyRemoteMapPresence</li>
</ul>

<li>NavigatorImpTest</li>

<ul>
<li>testGetPathWithoutSetIt</li>
<li>testSetGraph</li>
<li>testToNextRegion</li>
<li>testToNextRegionWithoutPathOrGraph</li>
<li>testToNextRegionWrongBeacon</li>
</ul>

<li>HomeActivityTest</li>

<ul>
<li>canIgetToNearbyPoiActivityTest</li>
</ul>

<li>CompassTest</li>

<ul>
<li>testRegisterListener</li>
</ul>

</ul>
Inoltre:

<ul>
<li>i test di sqldao possono falline se nelle vicinanze si trova un beacon</li>
<li>TS1 funziona ma solo spegnendo manualmente le connessioni internet(non sono riuscito a farlo automaticamente)</li>
</ul>

<b>NB i test sono stati lanciati tutti insieme con il comando ./gradlew connectedCheck quindi potrebbero essere o problemi di configurazione iniziale oppure per le modifiche che sono state apportate dalla loro creazione al codice</b>

**Comment by black2279** [comment]
(androidTest)
Per NavigatorImpTest bisogna decidere come gestire le eccezioni. (Esempio: path=null o graph=null)
CompassTest dipende dal delay.

(test)
~~TU5 fallisce perchè bisogna definire il tipo di ritorno per getNearbyPOI()~~
~~TU6 fallisce perchè non è definita la starterInformation~~

**Comment by o5k1** [comment]
I bottoni della Home vengono mostrati solo se l'app rileva un edificio conosciuto, penso quindi che canIgetToNearbyPoiActivityTest fallisca in quanto (in sede di test) non vengono rilevati beacon

**Comment by oeconti** [comment]
I test su BuildingService in teoria si sistemano con le modifiche fatte nel
branch DatabaseService.
Il 05/Giu/2016 18:35, "Andrea Tombolato" notifications@github.com ha
scritto:

**Comment by o5k1** [comment]
Ho provato canIgetToNearbyPoiActivityTest usando il telefono, funziona
