### ISSUE TITLE
DatabaseService - Policy

### ISSUE THREAD

**Issue by oeconti** [LeafSWE/clips#35]
Sono stati inseriti all'interno di DatabaseService gli ASyncTask per poter utilizzare la rete. Poiché la modifica tocca un'area un pò delicata vi chiedo di testare l'app e vedere che funzioni ancora.
A me e Marco funziona bene.

Appena mi dite faccio il merge.

**Comment by o5k1** [comment]
Ok per me

**Comment by black2279** [comment]
Ok

**Comment by o5k1** [comment]
Si può chiudere?
